language: ruby
rvm:
  - 2.2

branches:
  only:
  - master

before_script:
  - gem install asciidoctor
  - asciidoctor -v
  - make pipeline.version.startBuild
  - sed -i -- 's/0.1.0/0.1.'$TRAVIS_BUILD_NUMBER'.'$TRAVIS_BRANCH'/g' src/index.adoc

script:
  - make

after_success:
  - make pipeline.version.finishBuild
  - make pipeline.version.startDeploy
  - ls -l build/
  - |
      if [ -n "$GITHUB_API_KEY" ]; then
        cd "$TRAVIS_BUILD_DIR"
        cd build/
        rm .gitignore
        git init
        git checkout -b gh-pages
        git add .
        git -c user.name='travis' -c user.email='travis' commit -m "Generated for GitHub Pages"
        git push -f -q https://$GITHUB_API_KEY@github.com/DashboardHub/Documentation gh-pages &> /dev/null
        cd "$TRAVIS_BUILD_DIR"
      fi
  - make pipeline.version.finishDeploy
